---
title: "HW1"
author: "Hengxin Wu"
date: "2/1/2022"
output: html_document
---

# 2.4

## 8
### a
```{r}
college <- read.csv('/Users/hengxinwu/Desktop/512/Georgetown-Univerity/512/College.csv')
```

### b
```{r}
rownames(college) <- college[, 1]
View(college)
```

```{r}
college <- college[, -1]
View(college)
```

### c
#### i
```{r}
summary(college)
```

#### ii
```{r}
pairs(college[, 1:10])
```

### iii
```{r}
boxplot(college$Outstate ~ college$Private, main = "Outstate versus Private", xlab = "Private", ylab = "Outstate")
```

### iv
```{r}
Elite <- rep("No", nrow(college))
Elite[college$Top10perc > 50] <- "Yes" 
Elite <- as.factor(Elite)
college <- data.frame(college, Elite)
```

```{r}
summary(college)
```

```{r}
boxplot(college$Outstate ~ college$Elite, main = "Outstate versus Elite", xlab = "Elite", ylab = "Outstate")
```

# 3.7
## 3
### a
```{r}
# ^y = 50 + 20*GPA + 0.07*IQ + 35*LEVEL + 0.01*GPA*IQ - 10*GPA*LEVEL
# For College: ^y = 85 + 10*GPA + 0.07*IQ + 0.01*GPA*IQ
# For High School: ^y = 50 + 20*GPA + 0.07*IQ + 0.01*GPA*IQ
# The iii is correct beacuse ^y hight school > ^y college if GPA > 3.5
```

### b
```{r}
# ^y = 85 + 10*4.0 + 0.07*110 + 0.01*110*4.0 = 137.1
```

### c
```{r}
#False, because the coefficient can be the evidence, we should use F-test to test effect.
```

## 9






